name: Create and publish a Docker image

on:
  push:

jobs:
  build-and-push-image:
    strategy:
      fail-fast: false
      matrix:
        database-backend:
          - postgres
          - sqlite

    uses: docker/github-builder/.github/workflows/build.yml@3415a188caae9a0da7fba83bc06985776e0b1790 # v1.14.0
    permissions:
      contents: read
      packages: write
      id-token: write # Used for signing SLSA attestations
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    with:
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      build-args: |
        DATABASE_BACKEND=${{ matrix.database-backend }}

      cache: true
      cache-scope: ${{ github.repository }}-${{ matrix.database-backend }}
      cache-mode: max # max enables caching builder layers

      meta-images: ghcr.io/${{ github.repository }}
      meta-flavor: |
        suffix=-${{ matrix.database-backend }}
      meta-tags: |
        # Tag default branch as latest
        type=raw,value=latest,enable={{is_default_branch}}
        # Tag all branches with their name
        type=ref,event=branch,enable={{is_not_default_branch}}
